version: '3'

services:
  gin:
    image: golang:1.10.3-alpine3.8
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:9.3-alpine
    volumes:
      - .:/go/src/app
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_PASSWORD: sandbox
      POSTGRES_USER: sandbox
